First version
zurutech/zurutech.github.io pull request #68
Opened 2022-03-25 11:06 UTC by stefano-strati

The following is the omnicomprehensive template for the Pull Request.

Complete the section about your specific scenario.

### 1. Submit a new article

_Follow this template to check if your article can be submitted._

Please check to satisfy these requirements:

* [ ] Please check your author information: `/_data/authors.yml`: if it is not present add it.
* [ ] In the article meta the `tags` section is used for the team name. The team list can be find under the section `themeColor` in `_config.yml`: if your team is not present just add it.
* [ ] Double check the grammar using Grammarly: https://www.grammarly.com/ (using American English).
* [ ] If you can, reduce the code - you're explaining a concept, hence having lots of code makes the article only longer without adding a real information. Short code examples -> detailed description of the concept is the way to go.
* [ ] Keep the article formal - reduce/remove the slang expressions and the punctuations like `...` if not strictly necessary.
* [ ] Use the oxford comma (setting up Grammarly to use American English should forces you to use it)
* [ ] Do not hotlink images: put the images inside a subfolder in the images folder of the blog and link there. Double check the images copyright before using them.
* [ ] The ideal article should start from a problem -> the article content should start from it and describe the flow to solve it.

### 2. Fixing a typo

_Use this template to submit a merge request to fix a minor issue._

Please describe why this change is needed.

### 3. Fixing content
_Use this template to submit a pull request because the content of the article is wrong._

Please describe why this change is needed: why the content is wrong and what does this PR do.

2022-03-28 08:21 UTC, galeone requested changes

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +It often happens that when writing unit tests the SUT cannot be tested in isolation because it is dependent on other components. In such cases there are generally three possibilities:
SUT is an acronym that should be introduced before being used. Hence the first time write `System Under Test (SUT)`

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +- If the DOCs are not contained in the same module of the SUT you can opt for writing an integration test (or at least a higher level test than a unit test with respect to the Test Pyramid).
same for `DOC`

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +Although Test Doubles are also useful for writing sociable and integration unit tests, it is in writing isolated unit tests that they are most used, since in the latter you try to test the smallest p
The "Test Doubles" idea is something that needs to be introduced, because is not a concept every reader could be already familiar with

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +Although Test Doubles are also useful for writing sociable and integration unit tests, it is in writing isolated unit tests that they are most used, since in the latter you try to test the smallest p
also the acronym "COTS"

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +Although GoogleTest also offers an xUnit test framework, it was decided to rely on the Automation System provided by UE4 and to use only GoogleMock. As explained in the article by Von Ihno Lübbers (h
differences between xunit and unit test framework?

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +Although GoogleTest also offers an xUnit test framework, it was decided to rely on the Automation System provided by UE4 and to use only GoogleMock. As explained in the article by Von Ihno Lübbers (h
I'd replace "As explained in the article by Von Ihno Lübbers (https://www.maibornwolff.de/en/blog/how-we-create-real-unittests-unreal-engine-googlemock)" with

```md
As explained in the [article by Von Ihno Lübbers](https://www.maibornwolff.de/en/blog/how-we-create-real-unittests-unreal-engine-googlemock)
```

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +Although GoogleTest also offers an xUnit test framework, it was decided to rely on the Automation System provided by UE4 and to use only GoogleMock. As explained in the article by Von Ihno Lübbers (h
same for the other link

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +In the UE4 documentation (https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/BuildTools/UnrealBuildTool/ThirdPartyLibraries/) it is described how, once in possession of the binary files, to
```suggestion
In the [UE4 documentation](https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/BuildTools/UnrealBuildTool/ThirdPartyLibraries/) it is described how, once in possession of the binary files, to integrate third-party libraries, be they static or dynamic. In the next sections, we will explain why it was decided to compile GoogleTest as a dynamic library and illustrate the steps necessary to create it.
```

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +On Windows there is a problem with DLL Boundaries. This problem occurs when an object that is allocated in one DLL is passed by pointer to a second DLL that deallocates it. This can lead to memory er
CRT (acronym to introduce)

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +
Awesome. I suggest creating a gist with the `.patch` (created with `git diff`) and link it here. So a reader can just grab the patch and applying it.

Here's the Github gist link: https://gist.github.com/

Use your personal account for creating it,  no worries

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +Here are the steps to compile GoogleTest as a dynamic library for UE4 for Windows and Linux systems. To do this we will rely on CMake, as indicated in the guidelines provided by the library itself (h
```suggestion
Here are the steps to compile GoogleTest as a dynamic library for UE4 for Windows and Linux systems. To do this we will rely on CMake, as indicated in [the guidelines]((https://github.com/google/googletest/blob/main/googletest/README.md)) provided by the library itself.
```

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +2. Modify the library as indicated in the paragraph concerning DLL Boundaries
here you can also add the application of the patch from the gist

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +5. Since UE4 uses Clang 11.0.1 it is necessary to specify in the variable `LLVM_DIR` in the file `CMakeList.txt` defined above the path to the compiler
This is not true in general, UE 4.27 uses Clang 11.0.1 - specify the version

2022-03-28 08:21 UTC, galeone commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +        5. `make` (or `make -j4` to speed up the process)
```suggestion
        5. `make -j$(nproc)`
```

In this way is more idiomatic and it uses all the available cores

2022-03-28 13:08 UTC, stefano-strati commented on _posts/2022-03-25-integration-of-googletest-in-ue4-as-a-shared-library.md
> +Although GoogleTest also offers an xUnit test framework, it was decided to rely on the Automation System provided by UE4 and to use only GoogleMock. As explained in the article by Von Ihno Lübbers (h
Regarding the difference between xUnit and unit test framework, I will put the reference to the following link: https://en.wikipedia.org/wiki/XUnit

2022-03-30 09:42 UTC, galeone approved these changes

2022-03-30 11:40 UTC, merged